export const APP_EVENTS = {
  authCallbackSucceeded: 'auth_callback_succeeded',
  groupCreated: 'group_created',
  groupJoined: 'group_joined',
  groupInviteSent: 'group_invite_sent',
  groupInviteAccepted: 'group_invite_accepted',
  groupInviteDeclined: 'group_invite_declined',
  sessionJoinedByCode: 'session_joined_by_code',
  sessionScheduled: 'session_scheduled',
  sessionStarted: 'session_started',
  sessionEnded: 'session_ended',
  questionLaunched: 'question_launched',
  answerSubmitted: 'answer_submitted',
  answerRevealed: 'answer_revealed',
  billingSetupStarted: 'billing_setup_started',
  billingSetupCompleted: 'billing_setup_completed',
  subscriptionCheckoutStarted: 'subscription_checkout_started',
  subscriptionCheckoutCompleted: 'subscription_checkout_completed',
  billingPortalOpened: 'billing_portal_opened',
  stripeWebhookReceived: 'stripe_webhook_received',
  stripeWebhookSynced: 'stripe_webhook_synced',
  stripeWebhookIgnored: 'stripe_webhook_ignored',
  stripeWebhookSyncFailed: 'stripe_webhook_sync_failed',
  stripeInvoicePaymentFailed: 'stripe_invoice_payment_failed',
  leaderPassed: 'leader_passed',
} as const;

export type AppEventName = (typeof APP_EVENTS)[keyof typeof APP_EVENTS];
